// Auto-generated by tools/dev/sync_filetype_icons_from_server.py
// Do not edit by hand.

package com.pqnas.mobile.files

import com.pqnas.mobile.api.FileItemDto
import java.util.Locale

object FileTypeIcons {
    private const val DEFAULT_ICON = "default"
    private const val FOLDER_ICON = "folder"

    private val KNOWN_ICONS = setOf(
        "c",
        "cc",
        "cpp",
        "default",
        "dll",
        "folder",
        "generic_archive",
        "generic_audio",
        "generic_code",
        "generic_config",
        "generic_database",
        "generic_document",
        "generic_file",
        "generic_font",
        "generic_image",
        "generic_pdf",
        "generic_presentation",
        "generic_spreadsheet",
        "generic_text",
        "generic_video",
        "h",
        "html"
    )

    private val EXTENSION_ICON_ALIASES = mapOf(
        "7z" to "generic_archive",
        "aac" to "generic_audio",
        "apk" to "generic_archive",
        "avi" to "generic_video",
        "bak" to "generic_config",
        "bash" to "generic_code",
        "bmp" to "generic_image",
        "bz2" to "generic_archive",
        "cfg" to "generic_config",
        "conf" to "generic_config",
        "crt" to "generic_config",
        "css" to "generic_code",
        "csv" to "generic_spreadsheet",
        "cxx" to "generic_code",
        "db" to "generic_database",
        "deb" to "generic_archive",
        "dmg" to "generic_archive",
        "doc" to "generic_document",
        "docx" to "generic_document",
        "exe" to "generic_code",
        "flac" to "generic_audio",
        "gif" to "generic_image",
        "go" to "generic_code",
        "gz" to "generic_archive",
        "heic" to "generic_image",
        "hh" to "generic_code",
        "hpp" to "generic_code",
        "htm" to "generic_code",
        "html" to "generic_code",
        "hxx" to "generic_code",
        "ico" to "generic_image",
        "img" to "generic_archive",
        "ini" to "generic_config",
        "iso" to "generic_archive",
        "java" to "generic_code",
        "jpeg" to "generic_image",
        "jpg" to "generic_image",
        "js" to "generic_code",
        "json" to "generic_code",
        "jsx" to "generic_code",
        "key" to "generic_presentation",
        "kt" to "generic_code",
        "lock" to "generic_config",
        "log" to "generic_text",
        "lua" to "generic_code",
        "m4a" to "generic_audio",
        "m4v" to "generic_video",
        "md" to "generic_text",
        "mjs" to "generic_code",
        "mkv" to "generic_video",
        "mov" to "generic_video",
        "mp3" to "generic_audio",
        "mp4" to "generic_video",
        "msi" to "generic_archive",
        "odp" to "generic_presentation",
        "ods" to "generic_spreadsheet",
        "odt" to "generic_document",
        "ogg" to "generic_audio",
        "otf" to "generic_font",
        "pdf" to "generic_pdf",
        "pem" to "generic_config",
        "php" to "generic_code",
        "png" to "generic_image",
        "ppt" to "generic_presentation",
        "pptx" to "generic_presentation",
        "ps1" to "generic_code",
        "py" to "generic_code",
        "r" to "generic_code",
        "rar" to "generic_archive",
        "rb" to "generic_code",
        "rpm" to "generic_archive",
        "rs" to "generic_code",
        "rtf" to "generic_document",
        "scss" to "generic_code",
        "sh" to "generic_code",
        "so" to "generic_code",
        "sql" to "generic_database",
        "sqlite" to "generic_database",
        "svg" to "generic_image",
        "swift" to "generic_code",
        "tar" to "generic_archive",
        "tgz" to "generic_archive",
        "tiff" to "generic_image",
        "tmp" to "generic_config",
        "toml" to "generic_code",
        "ts" to "generic_code",
        "tsv" to "generic_video",
        "tsx" to "generic_code",
        "ttf" to "generic_font",
        "txt" to "generic_text",
        "wav" to "generic_audio",
        "webm" to "generic_video",
        "webp" to "generic_image",
        "woff" to "generic_font",
        "woff2" to "generic_font",
        "xls" to "generic_spreadsheet",
        "xlsx" to "generic_spreadsheet",
        "xml" to "generic_code",
        "xz" to "generic_archive",
        "yaml" to "generic_code",
        "yml" to "generic_code",
        "zip" to "generic_archive",
        "zsh" to "generic_code"
    )

    fun iconFor(item: FileItemDto): String {
        if (item.type == "dir") return FOLDER_ICON
        return iconForName(item.name)
    }

    fun iconForName(name: String?): String {
        if (name.isNullOrBlank()) return DEFAULT_ICON

        val trimmed = name.trim()
        val ext = trimmed.substringAfterLast('.', "").lowercase(Locale.ROOT)

        val mapped = EXTENSION_ICON_ALIASES[ext] ?: ext
        if (mapped.isNotBlank() && mapped in KNOWN_ICONS) {
            return mapped
        }

        return fallbackForExtension(ext)
    }

    fun assetPathFor(item: FileItemDto): String {
        return "filetypes/${iconFor(item)}.svg"
    }

    private fun fallbackForExtension(ext: String): String {
        if (ext.isBlank()) return DEFAULT_ICON

        return when (ext) {
            // Archives: prevents unknown archive extensions from falling back to a plain file icon.
            "zip", "7z", "rar", "tar", "gz", "tgz", "bz2", "xz", "deb", "rpm", "dmg", "apk" ->
                iconOrDefault("generic_archive")

            // Audio/video/image: keeps media files visually grouped even without a dedicated extension icon.
            "mp3", "wav", "ogg", "flac", "m4a", "aac" ->
                iconOrDefault("generic_audio")

            "mp4", "m4v", "mov", "mkv", "avi", "webm", "tsv" ->
                iconOrDefault("generic_video")

            "png", "jpg", "jpeg", "gif", "bmp", "svg", "webp", "tiff", "tif", "ico", "heic", "heif" ->
                iconOrDefault("generic_image")

            // Office/document files: avoids losing type hints when only generic master icons exist.
            "xls", "xlsx", "csv", "ods" ->
                iconOrDefault("generic_spreadsheet")

            "ppt", "pptx", "odp", "key" ->
                iconOrDefault("generic_presentation")

            "pdf" ->
                iconOrDefault("generic_pdf")

            "doc", "docx", "txt", "md", "rtf", "odt" ->
                iconOrDefault("generic_document")

            // Databases and code/config are common server-side files.
            "db", "sqlite", "sql" ->
                iconOrDefault("generic_database")

            "c", "cc", "cpp", "cxx", "h", "hh", "hpp", "hxx",
            "java", "kt", "ts", "tsx", "js", "jsx", "json",
            "html", "htm", "css", "scss", "php", "py", "rb",
            "rs", "go", "sh", "bash", "zsh", "lua", "swift",
            "xml", "yml", "yaml", "toml", "so", "dll", "exe",
            "ini", "cfg", "conf", "log" ->
                iconOrDefault("generic_code")

            else -> iconOrDefault("generic_file")
        }
    }

    private fun iconOrDefault(name: String): String {
        return if (name in KNOWN_ICONS) name else DEFAULT_ICON
    }
}
