#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import argparse
import shutil
import textwrap

# Keep this alias map aligned with DNA-Nexus server File Manager.
# It makes mobile use the same master icons as the server instead of old CPUNK per-extension icons.
ALIAS_GROUPS = {
    "generic_archive": [
        "7z", "apk", "bz2", "deb", "dmg", "gz", "img", "iso", "msi",
        "rar", "rpm", "tar", "tgz", "xz", "zip"
    ],
    "generic_audio": [
        "aac", "flac", "m4a", "mp3", "ogg", "wav"
    ],
    "generic_video": [
        "avi", "m4v", "mkv", "mov", "mp4", "tsv", "webm"
    ],
    "generic_image": [
        "bmp", "gif", "heic", "ico", "jpeg", "jpg", "png", "svg", "tiff", "webp"
    ],
    "generic_spreadsheet": [
        "csv", "ods", "xls", "xlsx"
    ],
    "generic_presentation": [
        "key", "odp", "ppt", "pptx"
    ],
    "generic_pdf": [
        "pdf"
    ],
    "generic_text": [
        "log", "md", "txt"
    ],
    "generic_document": [
        "doc", "docx", "odt", "rtf"
    ],
    "generic_config": [
        "bak", "cfg", "conf", "crt", "ini", "lock", "pem", "tmp"
    ],
    "generic_database": [
        "db", "sqlite", "sql"
    ],
    "generic_font": [
        "otf", "ttf", "woff", "woff2"
    ],
    "generic_code": [
        "bash", "css", "cxx", "exe", "go",
        "hh", "hpp", "htm", "html", "hxx", "java", "js", "json",
        "jsx", "kt", "lua", "mjs", "php", "ps1", "py", "r", "rb",
        "rs", "scss", "sh", "so", "swift", "toml", "ts", "tsx",
        "xml", "yaml", "yml", "zsh"
    ],
}

ALIASES = {
    ext: master
    for master, extensions in ALIAS_GROUPS.items()
    for ext in extensions
}


def kotlin_string_list(items: list[str]) -> str:
    return ",\n".join(f'        "{item}"' for item in items)


def kotlin_map_entries(items: dict[str, str]) -> str:
    return ",\n".join(
        f'        "{ext}" to "{master}"'
        for ext, master in sorted(items.items())
    )


def build_kotlin(master_icon_names: list[str]) -> str:
    names_block = kotlin_string_list(sorted(master_icon_names))
    alias_block = kotlin_map_entries(ALIASES)

    # assetPathFor() intentionally returns "filetypes/name.svg" because Android assets are
    # opened with context.assets.open(assetPath), not with file:///android_asset/ URLs.
    return f'''// Auto-generated by tools/dev/sync_filetype_icons_from_server.py
// Do not edit by hand.

package com.pqnas.mobile.files

import com.pqnas.mobile.api.FileItemDto
import java.util.Locale

object FileTypeIcons {{
    private const val DEFAULT_ICON = "default"
    private const val FOLDER_ICON = "folder"

    private val KNOWN_ICONS = setOf(
{names_block}
    )

    private val EXTENSION_ICON_ALIASES = mapOf(
{alias_block}
    )

    fun iconFor(item: FileItemDto): String {{
        if (item.type == "dir") return FOLDER_ICON
        return iconForName(item.name)
    }}

    fun iconForName(name: String?): String {{
        if (name.isNullOrBlank()) return DEFAULT_ICON

        val trimmed = name.trim()
        val ext = trimmed.substringAfterLast('.', "").lowercase(Locale.ROOT)

        val mapped = EXTENSION_ICON_ALIASES[ext] ?: ext
        if (mapped.isNotBlank() && mapped in KNOWN_ICONS) {{
            return mapped
        }}

        return fallbackForExtension(ext)
    }}

    fun assetPathFor(item: FileItemDto): String {{
        return "filetypes/${{iconFor(item)}}.svg"
    }}

    private fun fallbackForExtension(ext: String): String {{
        if (ext.isBlank()) return DEFAULT_ICON

        return when (ext) {{
            // Archives: prevents unknown archive extensions from falling back to a plain file icon.
            "zip", "7z", "rar", "tar", "gz", "tgz", "bz2", "xz", "deb", "rpm", "dmg", "apk" ->
                iconOrDefault("generic_archive")

            // Audio/video/image: keeps media files visually grouped even without a dedicated extension icon.
            "mp3", "wav", "ogg", "flac", "m4a", "aac" ->
                iconOrDefault("generic_audio")

            "mp4", "m4v", "mov", "mkv", "avi", "webm", "tsv" ->
                iconOrDefault("generic_video")

            "png", "jpg", "jpeg", "gif", "bmp", "svg", "webp", "tiff", "tif", "ico", "heic", "heif" ->
                iconOrDefault("generic_image")

            // Office/document files: avoids losing type hints when only generic master icons exist.
            "xls", "xlsx", "csv", "ods" ->
                iconOrDefault("generic_spreadsheet")

            "ppt", "pptx", "odp", "key" ->
                iconOrDefault("generic_presentation")

            "pdf" ->
                iconOrDefault("generic_pdf")

            "doc", "docx", "txt", "md", "rtf", "odt" ->
                iconOrDefault("generic_document")

            // Databases and code/config are common server-side files.
            "db", "sqlite", "sql" ->
                iconOrDefault("generic_database")

            "c", "cc", "cpp", "cxx", "h", "hh", "hpp", "hxx",
            "java", "kt", "ts", "tsx", "js", "jsx", "json",
            "html", "htm", "css", "scss", "php", "py", "rb",
            "rs", "go", "sh", "bash", "zsh", "lua", "swift",
            "xml", "yml", "yaml", "toml", "so", "dll", "exe",
            "ini", "cfg", "conf", "log" ->
                iconOrDefault("generic_code")

            else -> iconOrDefault("generic_file")
        }}
    }}

    private fun iconOrDefault(name: String): String {{
        return if (name in KNOWN_ICONS) name else DEFAULT_ICON
    }}
}}
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--server-root",
        default=str(Path.home() / "CLionProjects" / "pq-nas"),
        help="Path to the DNA-Nexus server repo root"
    )
    args = parser.parse_args()

    mobile_root = Path.cwd()
    server_root = Path(args.server_root).expanduser().resolve()

    src_dir = server_root / "apps" / "bundled" / "filemgr" / "src" / "www" / "icons" / "filetypes"
    dst_dir = mobile_root / "app" / "src" / "main" / "assets" / "filetypes"
    kotlin_out = mobile_root / "app" / "src" / "main" / "java" / "com" / "pqnas" / "mobile" / "files" / "FileTypeIcons.kt"

    if not src_dir.is_dir():
        print(f"[ERROR] Server icon source directory not found: {src_dir}")
        return 2

    icon_files = sorted(p for p in src_dir.glob("*.svg") if p.is_file())
    master_names = sorted(p.stem for p in icon_files)

    required = sorted({"default", "folder", "generic_file"} | set(ALIASES.values()))
    missing = [name for name in required if name not in master_names]
    if missing:
        print("[ERROR] Required server filetype icons are missing:")
        for name in missing:
            print(f"  - {name}.svg")
        print(f"Source checked: {src_dir}")
        return 2

    if not kotlin_out.parent.is_dir():
        print(f"[ERROR] Kotlin output directory not found: {kotlin_out.parent}")
        return 2

    dst_dir.mkdir(parents=True, exist_ok=True)

    # Delete old mobile SVGs first so removed/renamed server icons do not linger.
    for old in dst_dir.glob("*.svg"):
        old.unlink()

    copied = 0
    for src in icon_files:
        shutil.copy2(src, dst_dir / src.name)
        copied += 1

    kotlin_out.write_text(build_kotlin(master_names), encoding="utf-8")

    print(f"[OK] copied {copied} SVG icons")
    print(f"[OK] from: {src_dir}")
    print(f"[OK] to:   {dst_dir}")
    print(f"[OK] wrote {kotlin_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
